Document : [click here](https://tinyurl.com/python-pandas-day11)

In [1]:
from numpy import random
print(random.randint(1,100))#random integer in the given range
print(random.rand())#float number 0-1

30
0.28627551817377583


In [6]:
#creating n-dimensional array with random integer values
print(random.randint(100,size=(3)))
print(random.randint(100,size=(3,4)))
print(random.randint(100,size=(3,4,2)))

[48 36  4]
[[28 17 36  0]
 [80 83 98  9]
 [85  4 10 31]]
[[[62 89]
  [38 82]
  [99 98]
  [84 68]]

 [[52 42]
  [76 44]
  [70 83]
  [58 68]]

 [[99 26]
  [52 90]
  [60 59]
  [94 34]]]


In [8]:
#creating n-dimensional array with random floating-point values
print(random.rand())
print(random.rand(3))
print(random.rand(2,3))

0.16775173423640843
[0.55232164 0.39622632 0.80385619]
[[0.69872969 0.64515928 0.70914772]
 [0.46391354 0.7845288  0.9079815 ]]


In [13]:
#ravel() flattens array elements
a = random.randint(100,size=(3,2)).ravel()
a

array([27, 11, 41, 96, 92, 59])

In [14]:
#single element will be selected
random.choice(a)

27

In [16]:
#for generating an array with the given shape and elements from the given list
random.choice([1,2,3,4,5],size=(4,4))

array([[2, 1, 4, 2],
       [4, 1, 4, 2],
       [4, 3, 4, 1],
       [5, 1, 2, 1]])

### pandas:
1. Data manipulation,analysis and cleaning
2. we can work with Tabular,Unlabelled data

### Creating a DataFrame
1. using 2 dictionaries
2. simple dictionary --> DataFrame
3. using Series

In [21]:
#using 2 dictionaries
import pandas as pd
import numpy as np
dict1 = {'a':1,'b':2,'c':3,'d':4,'e':5}
dict2 = {'a':5,'b':6,'c':7,'d':8,'e':9}
data = {"First":dict1,"Second":dict2}
df = pd.DataFrame(data,dtype=np.int32)
df

First  Second
a      1       5
b      2       6
c      3       7
d      4       8
e      5       9

In [58]:
#simple dictionary --> DataFrame
d1 = {"Name":["preeti","mounika","sumathi"],"Address":["hyd","adb","AP"]}
df1 = pd.DataFrame(d1)
df1

Name Address
0   preeti     hyd
1  mounika     adb
2  sumathi      AP

In [25]:
#using Series
s1 = pd.Series([1,2,3,4,5,6,7,8,9,10])
s2 = pd.Series([12.23,23.34,45.3,45.5,67.4,67.78,34.45,23.34,67.4,23])
s3 = pd.Series(['a','b','c','d','e','f','g','h','i','j'])
data = {"column1":s1,"column2":s2,"column3":s3}
df3 = pd.DataFrame(data)
df3

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    45.30       c
3        4    45.50       d
4        5    67.40       e
5        6    67.78       f
6        7    34.45       g
7        8    23.34       h
8        9    67.40       i
9       10    23.00       j

### Selecting the data from the DataFrame:
1. loc --> Row and Column labels
2. iloc --> Row and Column index

In [32]:
type(df3)

pandas.core.frame.DataFrame

In [26]:
df3["column2"]

0    12.23
1    23.34
2    45.30
3    45.50
4    67.40
5    67.78
6    34.45
7    23.34
8    67.40
9    23.00
Name: column2, dtype: float64

In [27]:
df3[["column2","column3"]]

column2 column3
0    12.23       a
1    23.34       b
2    45.30       c
3    45.50       d
4    67.40       e
5    67.78       f
6    34.45       g
7    23.34       h
8    67.40       i
9    23.00       j

In [28]:
#single column
df3.loc[:,"column1"]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [31]:
#Extracting multiple column values
df3.loc[0:5,["column1","column2"]]

column1  column2
0        1    12.23
1        2    23.34
2        3    45.30
3        4    45.50
4        5    67.40
5        6    67.78

In [33]:
df3.iloc[:,0]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [34]:
df3.iloc[0:4,0:1]

column1
0        1
1        2
2        3
3        4

### Retrieving the information of DataFrame




In [35]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
column1    10 non-null int64
column2    10 non-null float64
column3    10 non-null object
dtypes: float64(1), int64(1), object(1)
memory usage: 320.0+ bytes


In [36]:
#returns no.of rows and columns of the DataFrame
df3.shape

(10, 3)

In [37]:
#returns columns of the DataFrame
df3.columns

Index(['column1', 'column2', 'column3'], dtype='object')

In [38]:
#returns rows indexes  of the DataFrame
df3.index

RangeIndex(start=0, stop=10, step=1)

### Viewing data from DataFrame:
1. head()
2. tail()
3. sample()

In [39]:
#First 5 rows
df3.head()

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    45.30       c
3        4    45.50       d
4        5    67.40       e

In [40]:
#First n rows
df3.head(3)

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    45.30       c

In [41]:
#last 5 rows
df3.tail()

column1  column2 column3
5        6    67.78       f
6        7    34.45       g
7        8    23.34       h
8        9    67.40       i
9       10    23.00       j

In [43]:
#returns last n rows
df3.tail(2)

column1  column2 column3
8        9     67.4       i
9       10     23.0       j

In [47]:
#returns a random row from the DataFrame
df3.sample()

column1  column2 column3
3        4     45.5       d

In [49]:
#returns a n random rows from the DataFrame
df3.sample(2)

column1  column2 column3
3        4     45.5       d
9       10     23.0       j

In [53]:
df3.describe()

column1    column2
count  10.00000  10.000000
mean    5.50000  40.974000
std     3.02765  20.997852
min     1.00000  12.230000
25%     3.25000  23.340000
50%     5.50000  39.875000
75%     7.75000  61.925000
max    10.00000  67.780000

In [54]:
#Renaming the column headers
df3 = df3.rename(columns={"column1":"First",
                          "column2":"Second",
                          "column3":"Third"})
df3

First  Second Third
0      1   12.23     a
1      2   23.34     b
2      3   45.30     c
3      4   45.50     d
4      5   67.40     e
5      6   67.78     f
6      7   34.45     g
7      8   23.34     h
8      9   67.40     i
9     10   23.00     j

In [61]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data , index=labels)
df

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes